In [22]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_splitin_test_split

In [15]:
r = pd.read_csv('data3.csv')
df = pd.DataFrame(r)
df
# for i in range(36):
#     df['k'][i]= df['k'][i].split(' ')
# for i in range(36):
#     df['k'][i] = df['k'][i][0] + ' '+ df['k'][i][5] + ' ' +df['k'][i][9] + ' ' + df['k'][i][11]


IR1  IR2   US
0      435  105  400
1     1095  105  129
2      555   75  100
3      195    0   85
4      105   75   81
5      105  105  400
6      120  105  166
7      240    0   27
8       75   90  212
9      105   75  198
10     255  105  182
11     120  150   84
12     120  120   75
13     135  120   66
14     180  120   45
15     165   75   29
16     255   60   85
17     105  105  400
18     180  150  400
19     240  135  320
20     210  105  164
21     255   90  400
22     285    0  314
23     390    0   70
24     135  105  236
25     255   90  218
26     165  120  128
27     135  120   95
28     225  135   77
29     165  150   59
...    ...  ...  ...
1248   210  135   26
1249     0  165   42
1250    90  105   51
1251    60  105   38
1252   330  180   24
1253    45  120   64
1254   105  135  400
1255    75  135  133
1256   135  135  400
1257   210  120   24
1258   150    0   12
1259    90   15   88
1260    90  105   88
1261    75  135   76
1262    60  105   63
1263   195  105   33
1264   180   30   21
1265   135  225   81
1266    90   90   63
1267    75  105   55
1268   195  105   68
1269   210  105   65
1270   105   90   57
1271    60  105   49
1272   180  135   37
1273    60   75   14
1274   165   15   20
1275   105   90  165
1276   225   90   24
1277   270  105   21

[1278 rows x 3 columns]

In [16]:
# for i in range(36):
#     df['k'][i] = list([df['k'][i][:9], df['k'][i][17],df['k'][i][25],df['k'][i][36]])

In [17]:
# df['left']= 5
# df['right']=6
# df['distance']= 8

# df

In [18]:
# for i in range(36):
#     df['distance'][i] = df['k'][i][3]
#     df['right'][i] = df['k'][i][2]
#     df['left'][i] = df['k'][i][1]


In [56]:
x = np.array(df['US'])
VL= np.array(df['IR1'])
VR = np.array(df['IR2'])
print(x)
print(VL)
print(VR)


[400 129 100 ... 165  24  21]
[ 435 1095  555 ...  105  225  270]
[105 105  75 ...  90  90 105]


In [58]:


print(x)
print(min(VL))
print(min(VR))

[400 129 100 ... 165  24  21]
0
0


In [49]:
X_train, X_test, y_train, y_test = train_test_split (x, VR, test_size=0.33, random_state=42)

In [50]:
X_train

array([0.18  , 0.065 , 1.    , 0.1025, 0.0625, 1.    , 0.265 , 0.285 ,
       0.0475, 0.33  , 0.1375, 0.335 , 0.3   , 0.1125, 1.    , 0.2775,
       1.    , 0.0925, 0.1075, 0.805 , 0.2775, 0.25  , 0.415 , 0.005 ,
       1.    , 1.    , 0.155 , 0.1775, 0.0525, 0.0675, 0.1325, 0.035 ,
       0.2375, 0.17  , 0.3875, 0.085 , 0.1575, 0.1525, 0.3025, 0.12  ,
       1.    , 1.    , 0.5125, 0.065 , 0.0275, 0.025 , 0.545 , 0.37  ,
       0.4525, 0.2275, 0.2025, 1.    , 0.41  , 0.195 , 0.185 , 0.29  ,
       0.3325, 0.215 , 0.9175, 0.2025, 0.6225, 0.2375, 1.    , 0.2975,
       0.2025, 0.1725, 0.7125, 0.125 , 0.7775, 0.2575, 0.26  , 0.295 ,
       0.3225, 0.3625, 0.2025, 0.3325, 0.28  , 0.5425, 0.0125, 0.0725,
       1.    , 0.225 , 0.985 , 0.205 , 0.2975, 0.255 , 1.    , 0.195 ,
       0.135 , 1.    , 0.0225, 0.1025, 0.1   , 0.2   , 1.    , 1.    ,
       0.03  , 1.    , 0.125 , 0.32  , 0.085 , 0.065 , 0.3175, 0.145 ,
       1.    , 0.85  , 0.13  , 0.38  , 0.2425, 0.15  , 0.415 , 0.1725,
      

In [38]:
def createA(x, D):
    '''
    Create the matrix A with degree D
    Input:
        x: np vector of shape (N,)
        D: degree of the model
    Output:
        A: np matrix of shape (N,D+1)
    '''
    ### BEGIN SOLUTION
    N = x.shape[0]
    A = np.ones((N,D+1))
    for d in range(1,D+1): # skipping d
        A[:,d] = np.power(x,d)
    ### END SOLUTION
    return A

In [39]:
def train_w(A, yd):
    '''
    Inputs:
        A: np matrix of shape (N,D+1)
        yd: np vector of shape (N,)
    Output:
        w: np vector of shape (D+1,)
    '''
    ### BEGIN SOLUTION
    N = yd.shape[0]
    D = A.shape[1]-1
    if N>D+1:
        w = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(yd)  # Least sq sol
    elif N<=D+1:
        w = A.T.dot(np.linalg.inv(A.dot(A.T))).dot(yd)  # Min-norm; add 0.00000001*np.eye(A.shape[0])

    ### END SOLUTION
    return w

In [40]:
def predict_y(w, x):
    '''
    Inputs:
        w: np vector of shape (D+1,)
        x: np vector of shape (N,)
    Outputs:
        y: np vector of shape (N,); y=Aw
    '''
    ### BEGIN SOLUTION
    D = w.shape[0]-1
    A = createA(x, D)
    y = A.dot(w)
    ### END SOLUTION
    return y

In [51]:
A = createA(X_train,3)
w = train_w(A,y_train)
result = predict_y(w,X_test)


In [52]:
result

array([0.10394529, 0.09500756, 0.10039479, 0.09637837, 0.10462536,
       0.0983363 , 0.10515163, 0.08507134, 0.10246605, 0.10320614,
       0.10159185, 0.09529099, 0.09962175, 0.09289086, 0.10074935,
       0.09856123, 0.10352771, 0.08753921, 0.10174711, 0.07803314,
       0.08945049, 0.10450759, 0.09856123, 0.09382672, 0.10272736,
       0.09829466, 0.10297399, 0.08591541, 0.09962175, 0.10450759,
       0.09829466, 0.08003464, 0.10259855, 0.07699749, 0.10430714,
       0.10423387, 0.10469843, 0.09698894, 0.10001652, 0.09556976,
       0.09921027, 0.09941811, 0.10223904, 0.09584389, 0.1036279 ,
       0.09157469, 0.09829466, 0.10456804, 0.10501856, 0.09556976,
       0.09829466, 0.08870159, 0.10515403, 0.0954934 , 0.09412906,
       0.09017883, 0.09039821, 0.09369724, 0.10415732, 0.09500756,
       0.10352771, 0.08003464, 0.103496  , 0.0973929 , 0.10297399,
       0.09921027, 0.08870159, 0.10159185, 0.1028525 , 0.10439072,
       0.08420552, 0.10110267, 0.08870159, 0.0837644 , 0.09471

In [43]:
def compute_mse(y, yd):
    '''
    Inputs:
        y: np vector of shape (N,); y=Aw
        yd: np vector of shape (N,); yd=f(x), ie., desired or true value
    Output:
        mse: mean squared error
    '''
    # YOUR CODE HERE
    mse = np.sum((y-yd)**2)/y.shape[0]
    print(mse.shape)
    return mse

In [53]:
mse = compute_mse(result,y_test)
print(mse)

()
0.0019047208621852368


In [54]:
w

array([ 0.07318582,  0.2262277 , -0.48602334,  0.28490448])